[project]
PROJECT_ABBR = "memo" # id of the project to be loaded from the gams-api

[ui]
VERSION = "0.0.0" # required version of the web app
TITLE = "MEMO WebUI" # (optional) title of the application

#
# Following properties are directly connected to the pollin tool commands 
# (handles environment specific configuration: development / production etc.)
#

[dev]
GAMS_API_ORIGIN = "http://localhost:18085" # address of the gams-api
IIIF_IMAGE_SERVER_ORIGIN = "http://localhost:18080" # adress of the IIIF server to be used
# allows to configure a path to where pollin tool produces it's files
# OUTPUT_PATH = "C:\\Users\\sebas\\Documents\\programming\\gams\\pollin-tool\\1"

[build]
GAMS_API_ORIGIN = "http://localhost:18085"
IIIF_IMAGE_SERVER_ORIGIN = "http://localhost:18080"

[dev.load]
OBJECT_COUNT_RESTRICTION = 2000000 # limits the number of objects loaded (+ used for rendering)
OBJECTS_REQUIRED = [
] # defines which objects are required to be loaded (ignoring the count restriction)

[build.load]
OBJECT_COUNT_RESTRICTION = 100000
OBJECTS_REQUIRED = [
]
